from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from ..models import Listing, Notification, RunSummary


class ListingRepository(Protocol):
    def migrate(self) -> None: ...
    def begin_run(self, automation: str) -> int: ...
    def finish_run(self, run_id: int, summary: RunSummary) -> None: ...
    def has_successful_run(self, automation: str) -> bool: ...
    def previous_observed_count(self, automation: str) -> int | None: ...
    def known_ids(self, source: str, external_ids: Sequence[str]) -> set[str]: ...
    def save_listings(self, listings: Sequence[Listing]) -> None: ...
    def enqueue_notification(
        self, automation: str, listing: Listing, notification: Notification
    ) -> None: ...
    def pending_notifications(self, automation: str) -> list[tuple[int, Notification]]: ...
    def mark_notification_sent(self, notification_id: int, backend: str) -> None: ...
    def close(self) -> None: ...
    def state(self, namespace: str, key: str, default=None): ...
    def set_state(self, namespace: str, key: str, value) -> None: ...
    def get_listing(self, source: str, external_id: str) -> Listing | None: ...
    def queue_event(self, automation: str, key: str, notification: Notification) -> None: ...
    def cancel_legacy_notifications(self, automation: str) -> None: ...
    def recent_listings(self, source: str, limit: int = 100) -> list[Listing]: ...
